apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: account
  name: account
  namespace: classninjia
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: account
status:
  loadBalancer: {}
