apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: course
  name: course
  namespace: classninjia
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: course
status:
  loadBalancer: {}
