apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: db
  namespace: classninjia
spec:
  # type: NodePort
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: db
status:
  loadBalancer: {}
